use_frameworks!

platform :ios, '8.0'

target 'Rudder-Appsflyer_Example' do
  pod 'Rudder-Appsflyer', :path => '../'

  target 'Rudder-Appsflyer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
