use_frameworks!

platform :ios, '12.0'

target 'Rudder-Appsflyer_Example' do
  pod 'Rudder-Appsflyer', :path => '../'

  
  post_install do |installer|
    # Xcode 26+ refuses deployment targets below iOS 15
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
  
end