use_frameworks!

platform :ios, '10.0'

target 'Rudder-Appsflyer_Example' do
  pod 'Rudder-Appsflyer', :path => '../'

  target 'Rudder-Appsflyer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
  
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  
end
