name: Deploy to Cocoapods

on:
  release:
    types: [created]
    
permissions:
  contents: read

jobs:
  build:
    name: Deploy to Cocoapods
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: macOS-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit

    - name: Checkout source branch
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Publish to CocoaPod
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push --allow-warnings
